src/prueba/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from biblioteca import views
from contactos.views  import contactos
from pokemon.views  import get_pokemon,info_pokemon,tipo_pokemon
"""

aumento 
xd
"""
urlpatterns = [
    
    url(r'^formulario-buscar/$', views.formulario_buscar),
    url(r'^buscar/$', views.buscar),
    url(r'^$', views.LibrosList.as_view(),name='libro_lista'),
    url(r'^nuevo/$', views.LibroCreate.as_view(),name='libro_nuevo'),
    url(r'^editar/(?P<pk>\d+)/$', views.LibroUpdate.as_view(),name='libro_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$', views.LibroDelete.as_view(),name='libro_eliminar'),
    url(r'^func/lista/$', views.libro_list,name='libro_funct_lista'),
    url(r'^func/nuevo/$', views.libro_add,name='libro_funct_nuevo'),
    url(r'^funct/editar/(?P<id_libro>\d+)/$', views.libro_edit,name='libro_funct_editar'),
    url(r'^funct/eliminar/(?P<id_libro>\d+)/$', views.libro_delete,name='libro_funct_eliminar'),
    # ---------------- Autor-----------------------------------------------
    url(r'^autor/lista/$', views.AutorList.as_view(),name='autor_lista'),
    url(r'^autor/nuevo/$', views.AutorCreate.as_view(),name='autor_nuevo'),
    url(r'^autor/editar/(?P<pk>\d+)/$', views.AutorUpdate.as_view(),name='autor_editar'),
    url(r'^autor/eliminar/(?P<pk>\d+)/$', views.AutorDelete.as_view(),name='autor_eliminar'),
    url(r'^autor/func/lista/$', views.autor_list,name='autor_funct_lista'),
    url(r'^autor/func/nuevo/$', views.autor_add,name='autor_funct_nuevo'),
    url(r'^autor/func/editar/(?P<id_autor>\d+)/$', views.autor_edit,name='autor_funct_editar'),
    url(r'^autor/func/eliminar/(?P<id_autor>\d+)/$', views.autor_delete,name='autor_funct_eliminar'),
    url(r'^contactos/$', contactos),
    # ---------------- pokemon-----------------------------------------------
    url(r'^pokemon/$', get_pokemon,name='index_pokemon'),
    url(r'^pokemon/detalle/(?P<id_pokemon>\d+)/$',info_pokemon,name='detalle_pokemon'),
    url(r'^pokemon/tipo/(?P<id_tipo>\d+)/$',tipo_pokemon,name='tipo_pokemon'),
]

src/contactos/forms.py
from django import forms 
 
class FormularioContactos(forms.Form): 
     asunto = forms.CharField(max_length=100) 
     email = forms.EmailField(required=False,label='Tu correo electronico') 
     mensaje = forms.CharField(widget=forms.Textarea)

src/contactos/views.py
from django.core.mail import send_mail 
from django.http import HttpResponseRedirect 
from django.shortcuts import render 
from contactos.forms import FormularioContactos
 
def contactos(request): 
    if request.method == 'POST': 
        form = FormularioContactos(request.POST) 
        if form.is_valid(): 
            cd = form.cleaned_data 
            send_mail( 
                cd['asunto'], 
                cd['mensaje'], 
                cd.get('email', 'noreply@example.com'), 
                    ['siteowner@example.com'], 
             ) 
            return HttpResponseRedirect('/contactos/gracias/') 
    else: 
        form = FormularioContactos(initial={'asunto': 'Adoro tu sitio!!!'}) 
    return render(request, 'formulario-contactos.html', {'form': form}) 

src/contactos/templates/formulario-contactos.html
<html> 
<head> 
    <title>Contactanos</title> 
</head> 
 
<body> 
    <h1>Contactanos</h1> 
 
 {% if form.errors %} 
    <p style="color: red;"> 
    Por favor corrige lo siguiente: 
    </p> 
{% endif %} 
 
    <form action="" method="post">{% csrf_token %} 
        <div class="field"> 
            {{ form.asunto.errors }} 
                <label for="id_asunto">Asunto:</label> 
            {{ form.asunto }} 
        </div> 
 
        <div class="field"> 
            {{ form.email.errors }} 
               <label for="id_email">E-mail:</label> 
           {{ form.email }} 
        </div> 
 
        <div class="field"> 
            {{ form.mensaje.errors }} 
                <label for="id_mensaje">Mensaje:</label> 
            {{ form.mensaje }} 
        </div> 
 
        <input type="submit" value="Enviar"> 
    </form> 
</body> 
</html>